name: "Generate and test features"
on:
  workflow_dispatch:

jobs:
  find-feature:
    if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
    runs-on: ubuntu-latest
    name: Find features
    outputs:
      generated_features: ${{ steps.feature-specs.outputs.generated_features }}
      all_features: ${{ steps.feature-specs.outputs.all_features }}

    steps:
      - uses: actions/checkout@v3
      - id: feature-specs
        uses: ./.github/actions/list-features-action
        with:
          path: .

  test:
    needs: [find-feature]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: ${{ fromJson( needs.find-feature.outputs.all_features )}}
        baseImage: ["mcr.microsoft.com/devcontainers/base:debian"]

    steps:
      - uses: actions/checkout@v3

      - name: Shell Linter
        uses: azohra/shell-linter@v0.6.0
        with:
          path: "src/**/*.sh"
          severity: "error" # [style, info, warning, error]
        env:
          SHELLCHECK_OPTS: -e SC2072 # Acceptable use of decimal comparison

      - name: "install generator"
        run: |
          pipx install cookiecutter
          pipx install shfmt-py

      - name: Generate
        id: generate
        run: |

          generated_features=$(sudo tree -J  ./feature_specs | sudo jq -c '.[0].contents | map(.name) | map(sub(".yaml"; ""))')
          set -e
          if  jq -e 'any(. == "${{ matrix.features }}")' <<< $generated_features; then
          cd ..
          cookiecutter ./features/pkgs/feature-template --overwrite-if-exists --no-input --config-file ./features/feature_specs/${{ matrix.features }}.yaml
          cd features
          fi

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
