on:
  push:
    branches: [main, dev-wiki]
    paths: [wiki/**, .github/workflows/Publish the dev wiki.yml]
jobs:
  Publish_the_wiki_folder_to_the_GitHub_Wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mv wiki/README.md wiki/Home.md
      - uses: impresscms-dev/strip-markdown-extensions-from-links-action@v0.3
        with:
          path: wiki
      - uses: stefanzweifel/git-auto-commit-action@v4
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "impresscms-dev/strip-markdown-extensions-from-links-action@v0.3"
          git push -f https://github.com/$GITHUB_REPOSITORY.wiki.git $(git subtree split -P wiki):master
